name: ci
run-name: Main CI actions
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened]
    branches: [ main ]
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run linters
        run: |
          bundle exec rubocop
  testing:
    name: Testing
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: pguser
          POSTGRES_DB: app
          POSTGRES_PASSWORD: password
        ports: ["5434:5432"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup test database
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_USER: pguser
          POSTGRES_DB: test_app
          POSTGRES_PASSWORD: password
        run: |
          bin/rails db:setup

      - name: Run tests
        run: bin/rails test
